language: python


matrix:
  include:
    # also check tox.ini
    - python: 3.6
      env:
        - DJANGO=1.11

    - python: 3.6
      env:
        - DJANGO=2.0

    - python: 3.6
      env:
        - DJANGO=2.1

    - python: 3.6
      env:
        - DJANGO=3.0

    # dist + sudo, see https://github.com/travis-ci/travis-ci/issues/9815 and
    #  https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905

    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - DJANGO=2.0

    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - DJANGO=2.1

    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - DJANGO=3.0

    - python: 3.8
      dist: xenial
      sudo: true
      env:
        - DJANGO=2.0

    - python: 3.8
      dist: xenial
      sudo: true
      env:
        - DJANGO=2.1

    - python: 3.8
      dist: xenial
      sudo: true
      env:
        - DJANGO=3.0

install:
  - pip install tox tox-travis

script:
  - tox

deploy:
  provider: pypi
  user: thorgate
  password:
    secure: >
      Ps6m8+VxrsYnNTKUdzeCihZWLzjfFYLj/OJsn6msfQKdZfWx1LAOOXBf2iv+xEz3yxrd7uCfrPhUHHSHYXWt653njEmQMX6cUGYD9/6DiCKLn
      C27tCL9QDtibXq2kn3KgLL7qWAtiJprAJr5SSuQrV3BUKpoN8CWLwyAsNDDCddKU9Y72AUH1usXVnnwweFbNDznCHcHcT2LTIR7BPWDZHElau
      EFqIZvZkblOjTC0TtS/jtnRFiEtDCdvzKSYuzehqTuoimhZq5sA4WmqbyaH7dI5G3ljXYDDFcV6trzL0e1eH3T+bX1XavE8GiuD0DSB8gpuWM
      ZecWJLNTp33BHxRj4KqRHiEWXTUmheJUuckjrxDZkuLOYp+3lNOo+CA/KWEB7yg4aEYAEgd1IWagJZSD01U5hLfjqv/VbazuG4iEIuKtKiKdf
      irugiTDkG2i906yorL7rJ3y2r1ubfvmWaQAkXmnnZbrh1mY/9vn83I/MWM0NrMUHUG3dBCujrPjR9xQQzocxbTbut9qFR2Xqk3okfgYV1sxVl
      FKrrV9jdGMz6xD5ZfK5eaRr4ml4UhRNDwcpcaEF6Lbbow59ThDZsgNvM63i8yawgO+iTj462V+BSX3dY0K5TRZhQCQCyAJXNEELzAVBM3w7xJ
      LSa40O7fWG3eOUzxYzS1VxzSWQykw=
  distributions: sdist bdist_wheel
  on:
    repo: thorgate/django-esteid
    tags: true
    python: "3.7"
    condition: "$DJANGO = 2.1"

notifications:
    email: false
