
version: '2.1'

services:
  django:
    build:
      context: ..
      dockerfile: idcard_auth_test/Dockerfile-django
    volumes:
      - "..:/app"
    command: python manage.py runserver 0.0.0.0:80

  nginx:
    image: nginx:1.19.3
    volumes:
      - "./etc.nginx:/etc/nginx"
    ports:
      - "8443:443"
    depends_on:
      - django
