FROM python:3.8-slim-buster

VOLUME /app

# Install poetry
ENV POETRY_HOME "$HOME/.poetry"
ENV POETRY_NO_INTERACTION 1
RUN wget https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py && \
    python3 get-poetry.py
ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"

COPY pyproject.toml /
COPY poetry.lock /

RUN pip install -r requirements-dev.txt

WORKDIR /app

CMD bash
