name: CI deploy

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup python for test ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Add poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: "1.1.11"
      - uses: actions/checkout@v2
      - name: Set poetry token
        run: poetry config http-basic.pypi __token__ ${{ secrets.POETRY_TOKEN }}
      - name: Publish to pypi
        run: poetry publish
