name: CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       include:
         - python: "3.8"
           DJANGO: "2.1"
           os: ubuntu-latest

         - python: "3.8"
           DJANGO: "3.0"
           os: ubuntu-latest

         - python: "3.9"
           DJANGO: "4.0"
           os: ubuntu-latest

         - python: "3.9"
           DJANGO: "4.1"
           os: ubuntu-latest

         - python: "3.11"
           DJANGO: "4.0"
           os: ubuntu-latest

         - python: "3.11"
           DJANGO: "4.1"
           os: ubuntu-latest
    steps:
      - name: Setup python for test ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Add poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: "1.4.0"
      - uses: actions/checkout@v2
      - name: Install tox
        run: python -m pip install tox
      - name: Run ci
        run: tox
        env:
          TOXENV: "py${{ matrix.python }}-django${{ matrix.DJANGO }}"
      - name: Publish coverage
        run: pip install coveralls && coveralls
        if: ${{ matrix.COVERALLS == '1' }}
        env:
          GITHUB_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
